%% phase5_export.m  --  Phase 5: discretize, validate, and export the controller
%
% Final handoff. Regenerates the discrete LQR gain from source, RE-VALIDATES it
% on the full realistic hardware chain (so the exported numbers are the ones that
% were proven to work), then writes:
%
%   results/rwip_gains.h     C header for the ESP32 firmware (gains, motor consts,
%                            loop rate, limits, fusion constants)
%   results/rwip_gains.mat   same package for MATLAB reuse
%
% Pairs with notes/phase5_handoff.md (the implementation spec). No firmware here.
%
% Run from the project root:  matlab -batch "run('scripts/phase5_export.m')"

%% ---- Paths & setup ------------------------------------------------------
clear; close all; clc;
rng(1);
thisFile  = mfilename('fullpath');
scriptDir = fileparts(thisFile);
projRoot  = fileparts(scriptDir);
addpath(fullfile(projRoot, 'src'));
resultsDir = fullfile(projRoot, 'results');
if ~exist(resultsDir, 'dir'); mkdir(resultsDir); end

p  = rwip_params();
[A, B, C, D] = rwip_linearize(p);
Ts = 1/200;
fHz = round(1/Ts);

%% ---- Re-derive the discrete LQR gain -----------------------------------
Q = diag([200, 5, 2e-4]);  Rw = 20;
sysd = c2d(ss(A,B,C,D), Ts, 'zoh');
[Ad, Bd] = ssdata(sysd);
Kd = dlqr(Ad, Bd, Q, Rw);
Kc = lqr(A, B, Q, Rw);
cl_poles = eig(Ad - Bd*Kd);

fprintf('==================================================================\n');
fprintf(' RWIP Phase 5 -- controller export / ESP32 handoff\n');
fprintf('==================================================================\n');
fprintf(' Discrete LQR @ %d Hz:  Kd = [% .6f  % .6f  % .6f]\n', fHz, Kd);
fprintf('   tau_cmd = -Kd*x = %.5f*theta + %.5f*theta_dot + %.6f*phi_dot  [N*m]\n', -Kd(1), -Kd(2), -Kd(3));
fprintf('   closed-loop |poles| (discrete): '); fprintf('%.4f ', abs(cl_poles)); fprintf('(all < 1 -> stable)\n\n');

%% ---- Re-validate the EXPORTED gain on the full realistic chain ----------
scfg.sigma_theta = deg2rad(0.30);
scfg.sigma_gyro  = deg2rad(0.25);
scfg.gyro_bias   = deg2rad(1.50);
scfg.sigma_wheel = 0.50;
simV = struct('Ts',Ts,'Tend',4.0,'controller',@ctrl_lqr,'cfg',struct('K',Kd), ...
              's0',struct(),'sensor',@sensor_imu,'scfg',scfg, ...
              'use_motor',true,'use_pwm',true,'pwm_bits',10,'use_motor_lag',true);
outV = simulate_sampled(p, [deg2rad(8);0;0], simV);
tail = outV.t >= 3.0;
rms_theta = rad2deg(sqrt(mean(outV.X(tail,1).^2)));
wheel_peak = max(abs(outV.X(:,3)));
ok = rms_theta < 2.0 && wheel_peak < p.V_max/p.Ke;
fprintf(' Validation (gyro bias+noise, motor lag, 10-bit PWM, %d Hz, from 8 deg):\n', fHz);
fprintf('   steady RMS theta = %.3f deg,  peak wheel = %.1f rad/s  -->  %s\n\n', ...
        rms_theta, wheel_peak, ternary(ok,'PASS','FAIL'));

%% ---- Derived firmware constants ----------------------------------------
R_over_Kt   = p.R / p.Kt;            % V per N*m (voltage from torque)
pwm_bits    = 10;
pwm_max     = 2^pwm_bits - 1;
theta_giveup= deg2rad(30);           % disable motor beyond this tilt
enable_win  = deg2rad(5);            % only start control within this of upright
wheel_soft  = 0.875 * (p.V_max/p.Ke);% soft wheel-speed limit (~350 rad/s)
comp_alpha  = 0.98;                  % complementary filter on theta
gyro_cal_N  = 2*fHz;                 % startup bias samples (2 s)

%% ---- Write the C header -------------------------------------------------
hpath = fullfile(resultsDir, 'rwip_gains.h');
fid = fopen(hpath, 'w');
fprintf(fid, '/*\n');
fprintf(fid, ' * rwip_gains.h  --  AUTO-GENERATED by scripts/phase5_export.m  (%s)\n', datestr(now,'yyyy-mm-dd'));
fprintf(fid, ' * Reaction-Wheel Inverted Pendulum -- LQR controller package (ESP32).\n');
fprintf(fid, ' *\n');
fprintf(fid, ' *   State  x = [theta, theta_dot, phi_dot]   (rad, rad/s, rad/s)\n');
fprintf(fid, ' *            theta   : arm angle from UPRIGHT, +CCW (0 = balanced)\n');
fprintf(fid, ' *            phi_dot : wheel speed RELATIVE TO ARM, +CCW\n');
fprintf(fid, ' *   Control tau_cmd = -(K_THETA*theta + K_THETADOT*theta_dot + K_PHIDOT*phi_dot)  [N*m]\n');
fprintf(fid, ' *   then  V = R_OVER_KT*tau_cmd + KE*phi_dot, clamp +/-V_MAX, PWM via DRV8833.\n');
fprintf(fid, ' *\n');
fprintf(fid, ' * Validated in sim @ %d Hz with gyro bias+noise, motor lag, 10-bit PWM:\n', fHz);
fprintf(fid, ' *   steady RMS theta = %.3f deg, peak wheel = %.1f rad/s (limit %.0f).\n', rms_theta, wheel_peak, p.V_max/p.Ke);
fprintf(fid, ' * See notes/phase5_handoff.md for the full loop spec.\n');
fprintf(fid, ' */\n#ifndef RWIP_GAINS_H\n#define RWIP_GAINS_H\n\n');

fprintf(fid, '/* ---- Control loop ---- */\n');
fprintf(fid, '#define RWIP_LOOP_HZ      %.1ff\n', 1/Ts);
fprintf(fid, '#define RWIP_LOOP_DT      %.6ff   /* seconds */\n\n', Ts);

fprintf(fid, '/* ---- Discrete LQR gain:  tau_cmd = -(K_THETA*th + K_THETADOT*thd + K_PHIDOT*phid) ---- */\n');
fprintf(fid, '#define RWIP_K_THETA      (%.6ff)   /* N*m per rad     */\n', Kd(1));
fprintf(fid, '#define RWIP_K_THETADOT   (%.6ff)   /* N*m per (rad/s) */\n', Kd(2));
fprintf(fid, '#define RWIP_K_PHIDOT     (%.6ff)   /* N*m per (rad/s) */\n\n', Kd(3));

fprintf(fid, '/* ---- Brushed-DC motor + driver ---- */\n');
fprintf(fid, '#define RWIP_KT           %.6ff   /* N*m/A  torque const   */\n', p.Kt);
fprintf(fid, '#define RWIP_KE           %.6ff   /* V*s/rad back-EMF const*/\n', p.Ke);
fprintf(fid, '#define RWIP_R            %.6ff   /* ohm  winding resist.  */\n', p.R);
fprintf(fid, '#define RWIP_R_OVER_KT    %.6ff   /* V per N*m             */\n', R_over_Kt);
fprintf(fid, '#define RWIP_V_MAX        %.3ff    /* V  (set to MEASURED bus voltage) */\n', p.V_max);
fprintf(fid, '#define RWIP_PWM_BITS     %d\n', pwm_bits);
fprintf(fid, '#define RWIP_PWM_MAX      %d\n\n', pwm_max);

fprintf(fid, '/* ---- Sensor fusion ---- */\n');
fprintf(fid, '#define RWIP_COMP_ALPHA   %.4ff   /* complementary filter: th = a*(th+gyro*dt)+(1-a)*th_acc */\n', comp_alpha);
fprintf(fid, '#define RWIP_GYRO_CAL_N   %d      /* startup gyro-bias samples (~2 s) */\n\n', gyro_cal_N);

fprintf(fid, '/* ---- Safety / startup limits ---- */\n');
fprintf(fid, '#define RWIP_ENABLE_WIN   %.4ff   /* rad ~%.0f deg: only enable control within this of upright */\n', enable_win, rad2deg(enable_win));
fprintf(fid, '#define RWIP_THETA_GIVEUP %.4ff   /* rad ~%.0f deg: cut motor beyond this (fallen) */\n', theta_giveup, rad2deg(theta_giveup));
fprintf(fid, '#define RWIP_WHEEL_SOFT   %.1ff   /* rad/s soft wheel-speed limit */\n\n', wheel_soft);

fprintf(fid, '#endif /* RWIP_GAINS_H */\n');
fclose(fid);
fprintf(' wrote %s\n', hpath);

%% ---- Save the .mat package ---------------------------------------------
mpath = fullfile(resultsDir, 'rwip_gains.mat');
gains = struct('Kd',Kd,'Kc',Kc,'Ts',Ts,'Q',Q,'R',Rw,'p',p, ...
               'R_over_Kt',R_over_Kt,'pwm_bits',pwm_bits, ...
               'theta_giveup',theta_giveup,'enable_win',enable_win, ...
               'wheel_soft',wheel_soft,'comp_alpha',comp_alpha,'gyro_cal_N',gyro_cal_N); %#ok<NASGU>
save(mpath, '-struct', 'gains');
fprintf(' wrote %s\n', mpath);

fprintf('==================================================================\n');
fprintf(' Phase 5 export %s.  Firmware spec: notes/phase5_handoff.md\n', ternary(ok,'OK','FAILED'));
fprintf('==================================================================\n');
if ~ok
    error('phase5:FAIL','Exported gains failed the realistic-chain validation.');
end

%% ---- helper -------------------------------------------------------------
function s = ternary(c,a,b)
    if c; s = a; else; s = b; end
end
